version: '3.9'
services:
  crawler-service:
    container_name: crawler-service
    build:
      context: crawler_service
      dockerfile: Dockerfile
    volumes:
      - ./crawler_service:/app/crawler_service
    ports:
      - "7001:7001"
    environment:
      - DISPLAY=:99
      - TZ=:Asia/Taipei
      - PYTHONPATH=:/app/crawler_service
    networks:
      - scraper-network

  database-service:
    container_name: database-service
    restart: always
    build:
      context: database_service
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    volumes:
      - ./database_service/data:/data/db
      - ./database_service/log:/var/log/mongodb
    environment:
      - MONGO_INITDB_DATABASE=web_scraper
      - TZ=:Asia/Taipei
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
    logging:
      driver: 'json-file'
      options:
        max-file: '10'
        max-size: '1024m'
    networks:
      - scraper-network

  cloud-service:
    container_name: cloud-service
    build:
      context: cloud_service
      dockerfile: Dockerfile
    volumes:
      - ./cloud_service:/app/cloud_service
    ports:
      - "7002:7002"
    environment:
      - TZ=:Asia/Taipei
      - PYTHONPATH=:/app/cloud_service
    networks:
      - scraper-network

networks:
  scraper-network: